// MOTION UF — card database (single source of truth for the client).
// Shape mirrors the CARDS table in docs/ARCHITECTURE.md.
// duration = seconds per set. players_* = 1 for the individual deck.
window.MUF_CARDS = [
  // ---------- INDIVIDUELL ----------
  {id:'MOT-IND-001',deck:'individual',category:'strength',name:'Armhävningar',description:'Klassisk armhävning med rak kropp.',difficulty:'medium',duration:40,instructions:['Händerna strax utanför axlarna.','Sänk bröstet mot golvet med rak kropp.','Pressa upp. Gå ner på knä vid behov.'],video_url:'',muscle_group:'överkropp',players_min:1,players_max:1},
  {id:'MOT-IND-002',deck:'individual',category:'strength',name:'Knäböj',description:'Grundböj med egen kroppsvikt.',difficulty:'easy',duration:40,instructions:['Fötterna axelbrett isär.','Skjut höften bakåt och böj knäna.','Res dig med tyngden i hälarna.'],video_url:'',muscle_group:'ben',players_min:1,players_max:1},
  {id:'MOT-IND-003',deck:'individual',category:'strength',name:'Utfallssteg',description:'Växelvisa utfall framåt.',difficulty:'medium',duration:40,instructions:['Ta ett långt steg framåt.','Sänk bakre knät mot golvet.','Tryck tillbaka och byt ben.'],video_url:'',muscle_group:'ben',players_min:1,players_max:1},
  {id:'MOT-IND-004',deck:'individual',category:'strength',name:'Planka',description:'Statisk planka på underarmarna.',difficulty:'medium',duration:40,instructions:['Armbågarna under axlarna.','Spänn magen och sätet.','Håll kroppen rak och andas lugnt.'],video_url:'',muscle_group:'bål',players_min:1,players_max:1},
  {id:'MOT-IND-005',deck:'individual',category:'strength',name:'Glute bridge',description:'Höftlyft på rygg.',difficulty:'easy',duration:40,instructions:['Ligg på rygg med böjda knän.','Lyft höften tills kroppen är rak.','Sänk långsamt och upprepa.'],video_url:'',muscle_group:'säte',players_min:1,players_max:1},
  {id:'MOT-IND-018',deck:'individual',category:'strength',name:'Knäböj med sträck',description:'Knäböj som avslutas med armarna över huvudet.',difficulty:'medium',duration:40,instructions:['Stå med fötterna axelbrett isär.','Sänk dig ner i en knäböj.','Res dig och sträck armarna över huvudet.'],video_url:'',muscle_group:'helkropp',players_min:1,players_max:1},
  {id:'MOT-IND-006',deck:'individual',category:'energy',name:'Jumping jacks',description:'Snabba sprättbensövningar.',difficulty:'easy',duration:40,instructions:['Hoppa isär med benen.','För armarna över huvudet samtidigt.','Hoppa ihop och upprepa i jämnt tempo.'],video_url:'',muscle_group:'helkropp',players_min:1,players_max:1},
  {id:'MOT-IND-007',deck:'individual',category:'energy',name:'Höga knän',description:'Löpning på stället med höga knän.',difficulty:'medium',duration:30,instructions:['Spring på stället.','Lyft knäna till höfthöjd.','Pumpa med armarna.'],video_url:'',muscle_group:'helkropp',players_min:1,players_max:1},
  {id:'MOT-IND-008',deck:'individual',category:'energy',name:'Burpees',description:'Ned i planka, upp i hopp.',difficulty:'hard',duration:30,instructions:['Sätt händerna i golvet.','Hoppa bakåt till planka och tillbaka.','Res dig och avsluta med ett hopp.'],video_url:'',muscle_group:'helkropp',players_min:1,players_max:1},
  {id:'MOT-IND-009',deck:'individual',category:'energy',name:'Mountain climbers',description:'Snabba knän mot bröstet i planka.',difficulty:'hard',duration:30,instructions:['Starta i hög planka.','Dra knäna växelvis mot bröstet.','Håll höften låg och stabil.'],video_url:'',muscle_group:'bål',players_min:1,players_max:1},
  {id:'MOT-IND-010',deck:'individual',category:'mobility',name:'Höftöppnare',description:'Djupt utfall med höften framåt.',difficulty:'easy',duration:45,instructions:['Gå ner i ett lågt utfall.','Skjut höften sakta framåt.','Byt sida halvvägs.'],video_url:'',muscle_group:'höft',players_min:1,players_max:1},
  {id:'MOT-IND-011',deck:'individual',category:'mobility',name:'Katt och ko',description:'Rörlighet för ryggen på alla fyra.',difficulty:'easy',duration:45,instructions:['Stå på alla fyra.','Runda ryggen uppåt när du andas ut.','Svanka mjukt när du andas in.'],video_url:'',muscle_group:'rygg',players_min:1,players_max:1},
  {id:'MOT-IND-012',deck:'individual',category:'mobility',name:'Bröstöppnare',description:'Stretch i dörröppning.',difficulty:'easy',duration:40,instructions:['Ställ dig i en dörröppning.','Armbågen i 90 grader mot karmen.','Luta dig lätt framåt. Byt sida.'],video_url:'',muscle_group:'bröst',players_min:1,players_max:1},
  {id:'MOT-IND-013',deck:'individual',category:'reset',name:'Box breathing',description:'Lugn andning i fyra takter.',difficulty:'easy',duration:60,instructions:['Andas in i fyra sekunder.','Håll andan i fyra.','Andas ut i fyra och håll i fyra.'],video_url:'',muscle_group:'andning',players_min:1,players_max:1},
  {id:'MOT-IND-014',deck:'individual',category:'reset',name:'Framåtfällning',description:'Häng avslappnat framåt.',difficulty:'easy',duration:45,instructions:['Stå med mjuka knän.','Fäll överkroppen framåt och låt den hänga.','Rulla långsamt upp kota för kota.'],video_url:'',muscle_group:'baksida',players_min:1,players_max:1},
  {id:'MOT-IND-015',deck:'individual',category:'reset',name:'Axelrullningar',description:'Släpp spänningar i nacke och axlar.',difficulty:'easy',duration:40,instructions:['Stå eller sitt rakt.','Rulla axlarna bakåt i stora cirklar.','Byt riktning efter halva tiden.'],video_url:'',muscle_group:'axlar',players_min:1,players_max:1},
  // ---------- FAMILJ & VÄNNER ----------
  {id:'MOT-FAM-023',deck:'family',category:'challenge',mode:'longest',name:'Vem håller längst?',description:'Alla går ner i planka samtidigt. Sist kvar vinner.',difficulty:'medium',duration:0,instructions:['Alla ställer sig i planka.','Starta klockan tillsammans.','Den som håller längst vinner rundan.'],video_url:'',muscle_group:'bål',players_min:2,players_max:8},
  {id:'MOT-FAM-011',deck:'family',category:'challenge',mode:'longest',name:'Väggsittningen',description:'Ryggen mot väggen, knän i 90 grader.',difficulty:'medium',duration:0,instructions:['Ryggen mot väggen.','Glid ner tills knäna är i 90 grader.','Den som sitter längst vinner.'],video_url:'',muscle_group:'ben',players_min:2,players_max:8},
  {id:'MOT-FAM-004',deck:'family',category:'challenge',mode:'race',name:'Flest knäböj',description:'30 sekunder. Flest godkända knäböj vinner.',difficulty:'medium',duration:30,instructions:['Ställ er bredvid varandra.','Räkna era egna knäböj.','Flest godkända efter 30 sekunder vinner.'],video_url:'',muscle_group:'ben',players_min:2,players_max:8},
  {id:'MOT-FAM-007',deck:'family',category:'challenge',mode:'race',name:'Stjärnhopp-duellen',description:'Flest jumping jacks på 30 sekunder.',difficulty:'easy',duration:30,instructions:['Ställ er på rad.','Kör jumping jacks i full fart.','Flest efter 30 sekunder vinner.'],video_url:'',muscle_group:'helkropp',players_min:2,players_max:8},
  {id:'MOT-FAM-015',deck:'family',category:'together',mode:'together',name:'Spegelspelet',description:'En leder, resten speglar rörelserna.',difficulty:'easy',duration:60,instructions:['Utse en ledare.','Ledaren rör sig långsamt.','Resten speglar. Byt ledare efter tiden.'],video_url:'',muscle_group:'helkropp',players_min:2,players_max:8},
  {id:'MOT-FAM-019',deck:'family',category:'together',mode:'together',name:'Planka-high-five',description:'Ge varandra high five i planka.',difficulty:'medium',duration:45,instructions:['Gå ner i planka mittemot varandra.','Ge high five med växlande händer.','Håll höften stilla hela tiden.'],video_url:'',muscle_group:'bål',players_min:2,players_max:8}
];
